name: NASA Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x]  # Matrix for testing Node.js v18.x versions

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your code

      - name: Set up Node.js version  ${{ matrix.node-version }}
        uses: actions/setup-node@v3  # Uses the latest stable version of setup-node
        with:
          node-version: ${{ matrix.node-version }}  # Uses version from matrix

      - name: Install dependencies
        run: npm install  # Installs all dependencies from package.json

      - name: Build client
        run: npm run build --prefix frontend  # Adjust the path if necessary to your actual folder

      - name: Run tests
        run: npm test  # Make sure there's a test script in package.json

