name: NASA Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your code

      - name: Set up Node.js version 18
        uses: actions/setup-node@v3  # Uses latest stable version of setup-node
        with:
          node-version: '18'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install  # Installs all dependencies from package.json

      - name: Build client
        run: npm run build --prefix frontend  # Builds the project in the 'frontend' directory

    
