name: NASA Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js version 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Debug frontend directory contents
        run: ls -la frontend  # Check if frontend folder exists

      - name: Build client with debugging
        run: |
          echo "Starting Build"
          npm run build --prefix frontend
          echo "Build finished"
        continue-on-error: true  # Allows the process to continue even if the build fails
